### ISSUE TITLE
torch 2.0 do not support torch.unint64

### ISSUE THREAD

**Issue by 3-leaves-grass** [chouliuzuo/GVMGen#5]
after  I pip install with your requirements.txt,  and run test.py   I  got the error   "module 'torch' has no attribute 'uint64'",  Actually,  The problem can be addressed by updating torch (>=2.3), However, AudioCraft requires PyTorch <=2.1.0,    what  I can do ?  

<img width="1636" height="708" alt="Image" src="https://github.com/user-attachments/assets/12957c9b-b440-44d9-8f9f-5f8c809047b0" />

**Comment by chouliuzuo** [comment]
I didn't meet this issue with torch==2.0.0, and I think you should check whether the transformers==4.35.1. By the way, I have tried that our code can work with torch==2.1.0 or even torch==2.7.0. So, maybe you could try installing torch with a higher version or uninstalling audiocraft.
